Задание 1  
Импортируйте библиотеки pandas и numpy.  
Загрузите "Boston House Prices dataset" из встроенных наборов данных библиотеки sklearn.  
Создайте датафреймы X и y из этих данных.  
  
Разбейте эти датафреймы на тренировочные (X_train, y_train) и тестовые (X_test, y_test)  
с помощью функции train_test_split так, чтобы размер тестовой выборки  
составлял 30% от всех данных, при этом аргумент random_state должен быть равен 42.  
  
Создайте модель линейной регрессии под названием lr с помощью класса LinearRegression   
из модуля sklearn.linear_model.  
  
Обучите модель на тренировочных данных (используйте все признаки) и сделайте   
предсказание на тестовых.  
Вычислите R2 полученных предказаний с помощью r2_score из модуля sklearn.metrics.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()

data = boston.data

target = boston.target

feature_names = boston.feature_names

feature_names

X = pd.DataFrame(data, columns=feature_names)

print(X.head())

y = pd.DataFrame(target, columns=['price'])

y.head()

      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0

   PTRATIO       B  LSTAT
0     15.3  396.90   4.98
1     17.8  396.90   9.14
2     17.8  392.83   4.03
3     18.7  394.63   2.94
4     18.7  396.90   5.33

   price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [13]:
y_pred = lr.predict(X_test)

In [14]:
from sklearn.metrics import r2_score

In [15]:
r2_score(y_test, y_pred)

0.7112260057484909

Задание 2  
Создайте модель под названием model с помощью RandomForestRegressor из модуля sklearn.ensemble.  
Сделайте агрумент n_estimators равным 1000,  
max_depth должен быть равен 12 и random_state сделайте равным 42.  
  
Обучите модель на тренировочных данных аналогично тому, как вы обучали модель LinearRegression,  
но при этом в метод fit вместо датафрейма y_train поставьте y_train.values[:, 0],  
чтобы получить из датафрейма одномерный массив Numpy,  
так как для класса RandomForestRegressor в данном методе для аргумента y предпочтительно     
применение массивов вместо датафрейма.  
  
Сделайте предсказание на тестовых данных и посчитайте R2. Сравните с результатом из предыдущего задания.  
Напишите в комментариях к коду, какая модель в данном случае работает лучше.

In [16]:
from sklearn.ensemble import RandomForestRegressor

In [17]:
from sklearn.model_selection import GridSearchCV

In [20]:
clf = RandomForestRegressor(max_depth = 12, n_estimators = 1000, random_state=42)
clf.fit(X_train, y_train.values[:, 0])
y_pred = clf.predict(X_test)

In [21]:
r2_score(y_test, y_pred)

0.8749965273218174

В данном случае, слуйчайный лес работает лучше, т.к. значение r2_score у него ближе к 1

* Задание 3  
Вызовите документацию для класса RandomForestRegressor,  
найдите информацию об атрибуте feature_importances_.  
  
С помощью этого атрибута найдите сумму всех показателей важности,  
установите, какие два признака показывают наибольшую важность.

In [24]:
? RandomForestRegressor

In [29]:
clf.feature_importances_
feature_importances = pd.Series(clf.feature_importances_, name='feature_importances')

In [30]:
feature_names = boston.feature_names

In [31]:
feature_names = boston.feature_names

data1 = pd.Series(feature_names, name='feature_names')

data = pd.concat([data1, feature_importances,], axis=1)
data

   feature_names  feature_importances
0           CRIM             0.032117
1             ZN             0.001550
2          INDUS             0.007094
3           CHAS             0.001149
4            NOX             0.014368
5             RM             0.402705
6            AGE             0.014245
7            DIS             0.064033
8            RAD             0.004968
9            TAX             0.011692
10       PTRATIO             0.018090
11             B             0.012311
12         LSTAT             0.415679

In [32]:
data['feature_importances'].sum()

0.9999999999999994

In [33]:
data.sort_values(by=['feature_importances'])

   feature_names  feature_importances
3           CHAS             0.001149
1             ZN             0.001550
8            RAD             0.004968
2          INDUS             0.007094
9            TAX             0.011692
11             B             0.012311
6            AGE             0.014245
4            NOX             0.014368
10       PTRATIO             0.018090
0           CRIM             0.032117
7            DIS             0.064033
5             RM             0.402705
12         LSTAT             0.415679

У признаков RM и LSTAT наибольшая важность  
Чем больше число, тем значимее признак. Сумма всех чисел равна 1.

* Задание 4  
В этом задании мы будем работать с датасетом, с которым мы уже   
знакомы по домашнему заданию по библиотеке Matplotlib, это датасет Credit Card Fraud Detection.  
  
Для этого датасета мы будем решать задачу классификации - будем определять,    
какие из транзакциции по кредитной карте являются мошенническими.  
  
Данный датасет сильно несбалансирован (так как случаи мошенничества относительно редки),  
так что применение метрики accuracy не принесет пользы и не поможет выбрать лучшую модель.  
Мы будем вычислять AUC, то есть площадь под кривой ROC.  
  
Импортируйте из соответствующих модулей RandomForestClassifier, GridSearchCV и train_test_split.  
  
Загрузите датасет creditcard.csv и создайте датафрейм df.  
С помощью метода value_counts с аргументом normalize=True убедитесь в том, что выборка несбалансирована.  
Используя метод info, проверьте, все ли столбцы содержат числовые данные и нет ли в них пропусков.  
  
Примените следующую настройку, чтобы можно было просматривать все столбцы датафрейма:  
pd.options.display.max_columns = 100.  
  
Просмотрите первые 10 строк датафрейма df.  
  
Создайте датафрейм X из датафрейма df, исключив столбец Class.   
Создайте объект Series под названием y из столбца Class.  
  
Разбейте X и y на тренировочный и тестовый наборы данных при помощи функции train_test_split,   
используя аргументы: test_size=0.3, random_state=100, stratify=y.  
У вас должны получиться объекты X_train, X_test, y_train и y_test.  
Просмотрите информацию о их форме.  
  
Для поиска по сетке параметров задайте такие параметры:  
parameters = [{'n_estimators': [10, 15],   
'max_features': np.arange(3, 5),  
'max_depth': np.arange(4, 7)}]  
  
Создайте модель GridSearchCV со следующими аргументами:  
estimator=RandomForestClassifier(random_state=100),  
param_grid=parameters,  
scoring='roc_auc',  
cv=3.  
  
Обучите модель на тренировочном наборе данных (может занять несколько минут).  
  
Просмотрите параметры лучшей модели с помощью атрибута best_params_.  
  
Предскажите вероятности классов с помощью полученнной модели и метода predict_proba.  
Из полученного результата (массив Numpy) выберите столбец с индексом 1 (вероятность класса 1)   
и запишите в массив y_pred_proba.    
  
Из модуля sklearn.metrics импортируйте метрику roc_auc_score.  
Вычислите AUC на тестовых данных и сравните с результатом,  
полученным на тренировочных данных, используя в качестве аргументов   
массивы y_test и y_pred_proba.

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

df = pd.read_csv('creditcard.csv')
df.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,-0.371407,1.341262,0.359894,-0.358091,-0.137134,0.517617,0.401726,-0.058133,0.068653,-0.033194,0.084968,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,-0.099254,-1.416907,-0.153826,-0.751063,0.167372,0.050144,-0.443587,0.002821,-0.611987,-0.045575,-0.219633,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,1.249376,-0.619468,0.291474,1.757964,-1.323865,0.686133,-0.076127,-1.222127,-0.358222,0.324505,-0.156742,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,-0.410430,-0.705117,-0.110452,-0.286254,0.074355,-0.328783,-0.210077,-0.499768,0.118765,0.570328,0.052736,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,-0.366846,1.017614,0.836390,1.006844,-0.443523,0.150219,0.739453,-0.540980,0.476677,0.451773,0.203711,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [37]:
df.Class.value_counts(normalize=True)

0    0.998273
1    0.001727
Name: Class, dtype: float64

In [51]:
pd.options.display.max_columns = 100

In [52]:
feature_names = np.array(df.columns.values.tolist())

In [53]:
len_f = np.where(feature_names == 'Class')
print(len_f)
feature_names = np.delete(feature_names, [len_f])
feature_names

(array([30], dtype=int64),)

array(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9',
       'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18',
       'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27',
       'V28', 'Amount'], dtype='<U6')

In [54]:
target = ['Class']

In [46]:
X = pd.DataFrame(df, columns=feature_names)
X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99

In [55]:
y = pd.DataFrame(df, columns=['Class'])
y.head()

   Class
0      0
1      0
2      0
3      0
4      0

In [56]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100, stratify=y)

In [57]:
parameters = [{'n_estimators': [10, 15], 
               'max_features': np.arange(3, 5),
               'max_depth': np.arange(4, 7)}]

clf = GridSearchCV(estimator=RandomForestClassifier(random_state=100), 
                   param_grid=parameters,
                   scoring='roc_auc',
                   cv=3)

In [58]:
clf.fit(X_train, y_train.values[:, 0])

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=100, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid=[{'n_estimators': [10, 15], 'max_features': array([3, 4]), 'max_depth': array([4, 5, 6])}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=0)

In [59]:
clf.best_params_

{'max_depth': 6, 'max_features': 3, 'n_estimators': 15}

In [60]:
y_pred_proba = clf.predict_proba(X_train)
y_pred_proba

array([[9.99717846e-01, 2.82154033e-04],
       [9.99717846e-01, 2.82154033e-04],
       [9.99717846e-01, 2.82154033e-04],
       ...,
       [9.99717846e-01, 2.82154033e-04],
       [9.99717846e-01, 2.82154033e-04],
       [9.99737336e-01, 2.62663815e-04]])

In [61]:
y_pred_proba =y_pred_proba[:,1]
y_pred_proba

array([0.00028215, 0.00028215, 0.00028215, ..., 0.00028215, 0.00028215,
       0.00026266])

In [62]:
from sklearn.metrics import roc_auc_score

In [63]:
roc_auc_score(y_train, y_pred_proba)

0.9703527882554751

*Дополнительные задания:  
1). Загрузите датасет Wine из встроенных датасетов sklearn.datasets с помощью функции  
load_wine в переменную data.  
2). Полученный датасет не является датафреймом. Это структура данных, имеющая ключи   
аналогично словарю. Просмотрите тип данных этой структуры данных и создайте список  
data_keys, содержащий ее ключи.  
3). Просмотрите данные, описание и названия признаков в датасете. Описание нужно   
вывести в виде привычного, аккуратно оформленного текста, без обозначений переноса   
строки, но с самими переносами и т.д.  
4). Сколько классов содержит целевая переменная датасета? Выведите названия классов.  
5). На основе данных датасета (они содержатся в двумерном массиве Numpy) и названий   
признаков создайте датафрейм под названием X.  
6). Выясните размер датафрейма X и установите, имеются ли в нем пропущенные значения.  
7). Добавьте в датафрейм поле с классами вин в виде чисел, имеющих тип данных   
numpy.int64. Название поля - 'target'.  
8). Постройте матрицу корреляций для всех полей X. Дайте полученному датафрейму   
название X_corr.

In [79]:
from sklearn.datasets import load_wine

wine = load_wine()

data = wine.data

data_keys = wine.keys()

In [89]:
class_1 = np.array(wine.target)
class_1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [90]:
unique_class = np.unique(wine.target, axis=0)
unique_class

array([0, 1, 2])

In [91]:
unique_class.shape

(3,)

In [92]:
feature_names = wine.feature_names
X = pd.DataFrame(data, columns=feature_names)

In [93]:
X.shape

(178, 13)

In [94]:
X.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [95]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
alcohol                         178 non-null float64
malic_acid                      178 non-null float64
ash                             178 non-null float64
alcalinity_of_ash               178 non-null float64
magnesium                       178 non-null float64
total_phenols                   178 non-null float64
flavanoids                      178 non-null float64
nonflavanoid_phenols            178 non-null float64
proanthocyanins                 178 non-null float64
color_intensity                 178 non-null float64
hue                             178 non-null float64
od280/od315_of_diluted_wines    178 non-null float64
proline                         178 non-null float64
dtypes: float64(13)
memory usage: 18.2 KB

In [99]:
Y = pd.DataFrame(wine.target, columns=['target'], dtype=np.int64)
X = pd.concat([X, Y,], axis=1)
X.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [100]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
alcohol                         178 non-null float64
malic_acid                      178 non-null float64
ash                             178 non-null float64
alcalinity_of_ash               178 non-null float64
magnesium                       178 non-null float64
total_phenols                   178 non-null float64
flavanoids                      178 non-null float64
nonflavanoid_phenols            178 non-null float64
proanthocyanins                 178 non-null float64
color_intensity                 178 non-null float64
hue                             178 non-null float64
od280/od315_of_diluted_wines    178 non-null float64
proline                         178 non-null float64
target                          178 non-null int64
dtypes: float64(13), int64(1)
memory usage: 19.5 KB

In [101]:
X_corr = X.corr()
X_corr.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
alcohol,1.000000,0.094397,0.211545,-0.310235,0.270798,0.289101,0.236815,-0.155929,0.136698,0.546364,-0.071747,0.072343,0.643720,-0.328222
malic_acid,0.094397,1.000000,0.164045,0.288500,-0.054575,-0.335167,-0.411007,0.292977,-0.220746,0.248985,-0.561296,-0.368710,-0.192011,0.437776
ash,0.211545,0.164045,1.000000,0.443367,0.286587,0.128980,0.115077,0.186230,0.009652,0.258887,-0.074667,0.003911,0.223626,-0.049643
alcalinity_of_ash,-0.310235,0.288500,0.443367,1.000000,-0.083333,-0.321113,-0.351370,0.361922,-0.197327,0.018732,-0.273955,-0.276769,-0.440597,0.517859
magnesium,0.270798,-0.054575,0.286587,-0.083333,1.000000,0.214401,0.195784,-0.256294,0.236441,0.199950,0.055398,0.066004,0.393351,-0.209179

In [102]:
high_corr = X_corr.abs()
high_corr

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
alcohol,1.000000,0.094397,0.211545,0.310235,0.270798,0.289101,0.236815,0.155929,0.136698,0.546364,0.071747,0.072343,0.643720,0.328222
malic_acid,0.094397,1.000000,0.164045,0.288500,0.054575,0.335167,0.411007,0.292977,0.220746,0.248985,0.561296,0.368710,0.192011,0.437776
ash,0.211545,0.164045,1.000000,0.443367,0.286587,0.128980,0.115077,0.186230,0.009652,0.258887,0.074667,0.003911,0.223626,0.049643
alcalinity_of_ash,0.310235,0.288500,0.443367,1.000000,0.083333,0.321113,0.351370,0.361922,0.197327,0.018732,0.273955,0.276769,0.440597,0.517859
magnesium,0.270798,0.054575,0.286587,0.083333,1.000000,0.214401,0.195784,0.256294,0.236441,0.199950,0.055398,0.066004,0.393351,0.209179
total_phenols,0.289101,0.335167,0.128980,0.321113,0.214401,1.000000,0.864564,0.449935,0.612413,0.055136,0.433681,0.699949,0.498115,0.719163
flavanoids,0.236815,0.411007,0.115077,0.351370,0.195784,0.864564,1.000000,0.537900,0.652692,0.172379,0.543479,0.787194,0.494193,0.847498
nonflavanoid_phenols,0.155929,0.292977,0.186230,0.361922,0.256294,0.449935,0.537900,1.000000,0.365845,0.139057,0.262640,0.503270,0.311385,0.489109
proanthocyanins,0.136698,0.220746,0.009652,0.197327,0.236441,0.612413,0.652692,0.365845,1.000000,0.025250,0.295544,0.519067,0.330417,0.499130
color_intensity,0.546364,0.248985,0.258887,0.018732,0.199950,0.055136,0.172379,0.139057,0.025250,1.000000,0.521813,0.428815,0.316100,0.265668
hue,0.071747,0.561296,0.074667,0.273955,0.055398,0.433681,0.543479,0.262640,0.295544,0.521813,1.000000,0.565468,0.236183,0.617369
od280/od315_of_diluted_wines,0.072343,0.368710,0.003911,0.276769,0.066004,0.699949,0.787194,0.503270,0.519067,0.428815,0.565468,1.000000,0.312761,0.788230
proline,0.643720,0.192011,0.223626,0.440597,0.393351,0.498115,0.494193,0.311385,0.330417,0.316100,0.236183,0.312761,1.000000,0.633717
target,0.328222,0.437776,0.049643,0.517859,0.209179,0.719163,0.847498,0.489109,0.499130,0.265668,0.617369,0.788230,0.633717,1.000000